### PR TITLE
Include libyang debs in the build output.

### PR DESCRIPTION
**Pull request by joshdcox**

### CODE REVIEW

**Comment by kevinkirkup** [comment]
Do we have to add our own versioning to differentiate from the upstream debian packages?

**Comment by joshdcox** [comment]
> Do we have to add our own versioning to differentiate from the upstream debian packages?

I don't think so. The libyang debs are just copied from a 3rd party. We don't build them, and they don't exist in the standard Ubuntu 18.04 repositories.

**Comment by kevinkirkup** [comment]
How about for FRR?

**Comment by joshdcox** [comment]
> How about for FRR?

The FRR packages include `-pureport1` in the version.

**Review by kevinkirkup — APPROVED** [review]

**Pull request merged**
